### ISSUE TITLE
Trunk doesn't compile with g++ 3.4.6

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#717]
bash-3.00$ uname -a
Linux gridfarm012.ucs.indiana.edu 2.6.9-5.ELsmp #1 SMP Wed Jan 5 19:29:47 EST 2005 x86_64 x86_64 x86_64 GNU/Linux

(Running RHEL 4)

Compiling from the latest trunk with g++ 3.4.6 fails, and it seems the error occurs in reaction.h 

In file included from cmlformat.cpp:22:
../../../include/openbabel/reaction.h:29:24: tr1/memory: No such file or directory
In file included from cmlformat.cpp:22:
../../../include/openbabel/reaction.h:44: error: `std::tr1' has not been declared

The complete output of make is attached

Reported by: @rajarshi
