### ISSUE TITLE
Breaking change of maeparser

### ISSUE THREAD

**Issue by e-kwsm** [openbabel/openbabel#2180]
Just for notification: recent maeparser change breaks compatibility (schrodinger/maeparser#62).

- [ ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 7684a772e6b60e6b37aa70ad05764d526ab9b00c
Operating system and version: Debian 10.3

## Expected Behavior

Build is successful.

## Actual Behavior

Build fails.

## Steps to Reproduce

```shellsession
$ rm -rf external/maeparser-master
$ cmake -GNinja -Bbuild .
$ cmake --build build -- src/formats/CMakeFiles/maeformat.dir/maeformat.cpp.o
../src/formats/maeformat.cpp: In member function ‘virtual bool OpenBabel::MAEFormat::WriteMolecule(OpenBabel::OBBase*, OpenBabel::OBConversion*)’:
../src/formats/maeformat.cpp:332:49: error: cannot bind rvalue reference of type ‘std::shared_ptr<schrodinger::mae::IndexedBlock>&&’ to lvalue of type ‘std::shared_ptr<schrodinger::mae::IndexedBlock>’
     ibm->addIndexedBlock(atom_block->getName(), atom_block);
                                                 ^~~~~~~~~~
In file included from ../external/maeparser-master/maeparser/Reader.hpp:8,
                 from ../src/formats/maeformat.cpp:33:
../external/maeparser-master/maeparser/MaeBlock.hpp:72:10: note:   initializing argument 2 of ‘void schrodinger::mae::IndexedBlockMap::addIndexedBlock(const string&, std::shared_ptr<schrodinger::mae::IndexedBlock>&&)’
     void addIndexedBlock(const std::string& name,
          ^~~~~~~~~~~~~~~
../src/formats/maeformat.cpp:333:49: error: cannot bind rvalue reference of type ‘std::shared_ptr<schrodinger::mae::IndexedBlock>&&’ to lvalue of type ‘std::shared_ptr<schrodinger::mae::IndexedBlock>’
     ibm->addIndexedBlock(bond_block->getName(), bond_block);
                                                 ^~~~~~~~~~
In file included from ../external/maeparser-master/maeparser/Reader.hpp:8,
                 from ../src/formats/maeformat.cpp:33:
../external/maeparser-master/maeparser/MaeBlock.hpp:72:10: note:   initializing argument 2 of ‘void schrodinger::mae::IndexedBlockMap::addIndexedBlock(const string&, std::shared_ptr<schrodinger::mae::IndexedBlock>&&)’
     void addIndexedBlock(const std::string& name,
          ^~~~~~~~~~~~~~~
```

**Comment by e-kwsm** [comment]
https://github.com/openbabel/openbabel/blob/7684a772e6b60e6b37aa70ad05764d526ab9b00c/CMakeLists.txt#L504

It would be better if pinned to a stable version.

**Comment by ghutchis** [comment]
@e-kwsm - thanks for the heads-up. I asked about this when they contributed and was assured it wouldn't be a problem. 🙄 

Let's pin to 1.2.3 for now?

**Comment by e-kwsm** [comment]
> Let's pin to 1.2.3 for now?

Build with maeparser 1.2.3 is successful, so I think we can.
