### ISSUE TITLE
OpenBabel 2.3.2 fails to compile on Gentoo Linux with GCC 6.3.0

### ISSUE THREAD

**Issue by fusion809** [openbabel/openbabel#1566]
- [x] I believe this to be a bug with Open Babel

## Environment Information
Open Babel version: 2.3.2
Operating system and version: Gentoo Linux, kernel is 4.11.0-gentoo

## Expected Behaviour
The build would work and OpenBabel would be installed with Portage without a flaw. 

## Actual Behaviour
Using Portage I was trying to build this app using [this ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/sci-chemistry/openbabel/openbabel-2.3.2-r1.ebuild?id=43c10326958cf85bccdb6270b5963cba45052412). The compilation failed rather early on with this build error:

```bash
[  2%] Building CXX object src/CMakeFiles/openbabel.dir/chargemodel.o
cd /var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2_build/src && /usr/bin/x86_64-pc-linux-gnu-g++ -DHAVE_EIGEN -DHAVE_EIGEN3 -DHAVE_LIBZ -DHAVE_SHARED_POINTER -DHAVE_WXWIDGETS -DMAKE_OBDLL -DUSING_DYNAMIC_LIBS -DWXUSINGDLL -D_FILE_OFFSET_BITS=64 -D__WXGTK__ -isystem /usr/lib64/wx/include/gtk2-unicode-3.0 -isystem /usr/include/wx-3.0 -I/var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2_build/include -I/var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/data -I/var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/include -I/usr/include/eigen3   -DNDEBUG -DNDEBUG -O2 -pipe -pthread -fopenmp -fPIC   -DOB_MODULE_PATH="\"/usr/lib64/openbabel/2.3.2\"" -o CMakeFiles/openbabel.dir/chargemodel.o -c /var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/src/chargemodel.cpp
/var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/src/alias.cpp: In static member function ‘static bool OpenBabel::AliasData::LoadFile(OpenBabel::AliasData::SmartsTable&)’:
/var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/src/alias.cpp:273:9: error: reference to ‘shared_ptr’ is ambiguous
         shared_ptr<OBSmartsPattern> psp(new OBSmartsPattern);
         ^~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include/g++-v6/tr1/memory:50:0,
                 from /var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/include/openbabel/shared_ptr.h:25,
                 from /var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/include/openbabel/alias.h:19,
                 from /var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/src/alias.cpp:17:
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include/g++-v6/tr1/shared_ptr.h:501:11: note: candidates are: template<class _Tp> class std::tr1::shared_ptr
     class shared_ptr;
           ^~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include/g++-v6/bits/shared_ptr.h:52:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include/g++-v6/memory:82,
                 from /var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/include/openbabel/shared_ptr.h:23,
                 from /var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/include/openbabel/alias.h:19,
                 from /var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/src/alias.cpp:17:
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include/g++-v6/bits/shared_ptr_base.h:343:11: note:                 template<class _Tp> class std::shared_ptr
     class shared_ptr;
           ^~~~~~~~~~
/var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/src/alias.cpp:273:35: error: expected primary-expression before ‘>’ token
         shared_ptr<OBSmartsPattern> psp(new OBSmartsPattern);
                                   ^
/var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/src/alias.cpp:273:60: error: ‘psp’ was not declared in this scope
         shared_ptr<OBSmartsPattern> psp(new OBSmartsPattern);
                                                            ^
[  2%] Building CXX object src/CMakeFiles/openbabel.dir/chiral.o
cd /var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2_build/src && /usr/bin/x86_64-pc-linux-gnu-g++ -DHAVE_EIGEN -DHAVE_EIGEN3 -DHAVE_LIBZ -DHAVE_SHARED_POINTER -DHAVE_WXWIDGETS -DMAKE_OBDLL -DUSING_DYNAMIC_LIBS -DWXUSINGDLL -D_FILE_OFFSET_BITS=64 -D__WXGTK__ -isystem /usr/lib64/wx/include/gtk2-unicode-3.0 -isystem /usr/include/wx-3.0 -I/var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2_build/include -I/var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/data -I/var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/include -I/usr/include/eigen3   -DNDEBUG -DNDEBUG -O2 -pipe -pthread -fopenmp -fPIC   -DOB_MODULE_PATH="\"/usr/lib64/openbabel/2.3.2\"" -o CMakeFiles/openbabel.dir/chiral.o -c /var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/src/chiral.cpp
[  2%] Building CXX object src/CMakeFiles/openbabel.dir/data.o
cd /var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2_build/src && /usr/bin/x86_64-pc-linux-gnu-g++ -DHAVE_EIGEN -DHAVE_EIGEN3 -DHAVE_LIBZ -DHAVE_SHARED_POINTER -DHAVE_WXWIDGETS -DMAKE_OBDLL -DUSING_DYNAMIC_LIBS -DWXUSINGDLL -D_FILE_OFFSET_BITS=64 -D__WXGTK__ -isystem /usr/lib64/wx/include/gtk2-unicode-3.0 -isystem /usr/include/wx-3.0 -I/var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2_build/include -I/var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/data -I/var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/include -I/usr/include/eigen3   -DNDEBUG -DNDEBUG -O2 -pipe -pthread -fopenmp -fPIC   -DOB_MODULE_PATH="\"/usr/lib64/openbabel/2.3.2\"" -o CMakeFiles/openbabel.dir/data.o -c /var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2/src/data.cpp
make[2]: *** [src/CMakeFiles/openbabel.dir/build.make:63: src/CMakeFiles/openbabel.dir/alias.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2_build'
make[1]: *** [CMakeFiles/Makefile2:1196: src/CMakeFiles/openbabel.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/sci-chemistry/openbabel-2.3.2-r1/work/openbabel-2.3.2_build'
make: *** [Makefile:141: all] Error 2
```

My full build log (showing the source configuration using cmake and the entire compilation output) is [here](https://paste.pound-python.org/show/UBYYuKH3qSq84yOe2ux4/). 

`emerge -pqv '=sci-chemistry/openbabel-2.3.2-r1::gentoo'` returns (to show the USE flags, which affect configure options, refer to the ebuild linked earlier for how):

```bash
[ebuild  N    ] sci-chemistry/openbabel-2.3.2-r1  USE="openmp wxwidgets -doc {-test}"
```

The output of `emerge --info '=sci-chemistry/openbabel-2.3.2-r1::gentoo'` (which will show details about my Gentoo system, like compiler options):

```bash
Portage 2.3.5 (python 3.4.6-final-0, default/linux/amd64/13.0/desktop/plasma/systemd, gcc-6.3.0, glibc-2.24-r1, 4.11.0-gentoo x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-4.11.0-gentoo-x86_64-Intel-R-_Core-TM-_i7-4700MQ_CPU_@_2.40GHz-with-gentoo-2.3
KiB Mem:    16344248 total,  10297040 free
KiB Swap:          0 total,         0 free
sh bash 4.4_p12
ld GNU ld (Gentoo 2.27 p1.0) 2.27
app-shells/bash:          4.4_p12::gentoo
dev-java/java-config:     2.2.0-r3::gentoo
dev-lang/perl:            5.24.1-r1::gentoo
dev-lang/python:          2.7.13::gentoo, 3.4.6::gentoo
dev-util/cmake:           3.8.1::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.3::gentoo
sys-apps/openrc:          0.26.1::gentoo
sys-apps/sandbox:         2.10-r4::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69-r3::gentoo
sys-devel/automake:       1.12.6-r1::gentoo, 1.13.4-r1::gentoo, 1.15-r2::gentoo
sys-devel/binutils:       2.27::gentoo
sys-devel/gcc:            6.3.0::gentoo
sys-devel/gcc-config:     1.8-r1::gentoo
sys-devel/libtool:        2.4.6-r4::gentoo
sys-devel/make:           4.2.1-r1::gentoo
sys-kernel/linux-headers: 4.10::gentoo (virtual/os-headers)
sys-libs/glibc:           2.24-r1::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: git
    sync-uri: https://github.com/gentoo/gentoo.git
    priority: -1000

fusion809
    location: /usr/local/fusion809-overlay
    masters: gentoo

flatpak-overlay
    location: /usr/local/flatpak-overlay
    sync-type: git
    sync-uri: git://github.com/fosero/flatpak-overlay.git
    masters: gentoo
    priority: 50

gamerlay
    location: /var/lib/layman/gamerlay
    sync-type: git
    sync-uri: git://anongit.gentoo.org/proj/gamerlay.git
    masters: gentoo
    priority: 50

games-overlay
    location: /var/lib/layman/games-overlay
    sync-type: git
    sync-uri: git://github.com/hasufell/games-overlay.git
    masters: gentoo
    priority: 50

gnome
    location: /var/lib/layman/gnome
    sync-type: git
    sync-uri: git://github.com/gentoo/gnome.git
    masters: gentoo
    priority: 50

grub2-themes
    location: /var/lib/layman/grub2-themes
    sync-type: git
    sync-uri: git://github.com/gentoo/grub2-themes-overlay.git
    masters: gentoo
    priority: 50

mozilla
    location: /var/lib/layman/mozilla
    sync-type: git
    sync-uri: git://anongit.gentoo.org/proj/mozilla.git
    masters: gentoo
    priority: 50

spring
    location: /var/lib/layman/spring-overlay
    sync-type: git
    sync-uri: git://github.com/springlobby/overlay.git
    masters: gentoo
    priority: 50

steam-overlay
    location: /var/lib/layman/steam-overlay
    sync-type: git
    sync-uri: git://github.com/anyc/steam-overlay.git
    masters: gentoo
    priority: 50

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-O2 -pipe"
DISTDIR="/usr/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://ftp.swin.edu.au/gentoo"
LANG="en_AU.UTF-8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j9"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac acl acpi alsa amd64 berkdb branding bumblebee bzip2 cairo cdda cdr cli cracklib crypt cups cxx dbus declarative dri dts dvd dvdr emboss encode exif fam firefox flac fortran gdbm gif glamor gpm gtk iconv ipv6 jpeg kde kipi kms kwallet lcms ldap libnotify mad mng modules mp3 mp4 mpeg multilib ncurses nls nptl nvidia ogg opengl openmp pam pango pcre pdf phonon plasma png policykit ppds qml qt3support qt4 qt5 readline sdl seccomp semantic-desktop session spell ssl startup-notification svg systemd tcpd tiff truetype udev udisks unicode upower usb vorbis wayland widgets wxwidgets x264 xattr xcb xcomposite xinerama xml xscreensaver xv xvid xwayland zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="evdev synaptics" KERNEL="linux" L10N="en en_AU en_GB en_US en-AU en-GB en-US" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6" PYTHON_SINGLE_TARGET="python3_4" PYTHON_TARGETS="python2_7 python3_4" RUBY_TARGETS="ruby21 ruby22" USERLAND="GNU" VIDEO_CARDS="nvidia intel" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON
```

## Steps to Reproduce
On a 64-bit Gentoo Linux testing system (with `ACCEPTED_KEYWORDS="~amd64"` in `/etc/portage/make.conf`) run:

```bash
emerge '=sci-chemistry/openbabel-2.3.2-r1::gentoo'
```

as root, with the options showed in the above `emerge --info` output. 

Thanks for your time,
Brenton

**Comment by ghutchis** [comment]
You're trying to compile a 2012 version of Open Babel (i.e., ancient) with a compiler from 2016.

I'd suggest trying either v2.4.1, or alternately the GitHub version. You may need this patch:
https://github.com/openbabel/openbabel/commit/1bde79933149fb02c2e5b50d3a2f80a82f39c508

But I don't see how I can keep *old* versions of the code compatible with *new* versions of compilers.

**Comment by fusion809** [comment]
Sorry mate, rofl, I assumed Gentoo would have the latest version. Faulty assumption, shall not be made again! Generally speaking Gentoo is a bleeding-edge distro.

**Comment by fusion809** [comment]
Configuration now fails. This is the error:

```bash
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
CMake Warning (dev) at /usr/share/cmake/Modules/FindOpenMP.cmake:179 (if):
  if given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindOpenMP.cmake:224 (_OPENMP_GET_SPEC_DATE)
  CMakeLists.txt:397 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
CMake Warning (dev) at /usr/share/cmake/Modules/FindOpenMP.cmake:179 (if):
  if given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindOpenMP.cmake:266 (_OPENMP_GET_SPEC_DATE)
  CMakeLists.txt:397 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

```

this is with 2.4.1. I tried applying that patch but it makes no difference to this issue.

**Comment by fusion809** [comment]
Build works, just some cmake warnings I reported earlier.
