### PR TITLE
Add missing include of <ctime> to fix build with glibc 2.36

### PR DESCRIPTION
**Pull request by schnitzeltony**
| include/openbabel/obutil.h:65:14: error: 'clock' was not declared in this scope
|    65 |       start= clock();
|       |              ^~~~~
| include/openbabel/obutil.h:40:1: note: 'clock' is defined in header '<ctime>'; did you forget to '#include <ctime>'?
|    39 | #include <math.h>
|   +++ |+#include <ctime>
|    40 |
| include/openbabel/obutil.h: In member function 'double OpenBabel::OBStopwatch::Lap()':
| include/openbabel/obutil.h:70:13: error: 'clock' was not declared in this scope
|    70 |       stop= clock();
|       |             ^~~~~
| include/openbabel/obutil.h:70:13: note: 'clock' is defined in header '<ctime>'; did you forget to '#include <ctime>'?
| include/openbabel/obutil.h:71:40: error: 'CLOCKS_PER_SEC' was not declared in this scope
|    71 |       return((stop - start) / (double) CLOCKS_PER_SEC);
|       |                                        ^~~~~~~~~~~~~~
| include/openbabel/obutil.h:71:40: note: the macro 'CLOCKS_PER_SEC' had not yet been defined

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>

### CODE REVIEW

**Comment by fredrikw** [comment]
Probably fixed by #2493? According to the comments in #2529

**Comment by cryos** [comment]
I was just looking into this as we are using the 3.1.1 release in the Avogadro superbuild. The fix already applied resolves this issue for me. I could use a new release to pin our build to, but I have patched locally and see everything works. I would recommend closing this pull request.

**Comment by ghutchis** [comment]
Thanks - this seems to be fixed by #2844 - I'm closing this as a duplicate
