### ISSUE TITLE
Angle, Pair, Torsion iterators dones not have deref() method

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#732]
OBMolAngleIter, OBMolPairIter, OBMolTorsionIter doesn't work with Python bindings (OpenBabel 2.1.1, Linux).
Produced error:

Traceback (most recent call last):
  File "./getCon.py", line 71, in ?
    print angleIter.next()
  File "./getCon.py", line 61, in next
    obAngle = self.iter.deref()
AttributeError: 'OBMolAngleIter' object has no attribute 'deref'

Reported by: *anonymous
